server:
  port: 8080

spring:
  #database config
  datasource:
    url: jdbc:mysql://localhost:3306/ch2?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 20020830wyb2618
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8
  #static config
  #thymeleaf engine config
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  web:
    resources:
      static-locations: classpath:static/

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.ch2.bean